server:
  port: 8091
spring:
  application:
    name: zuul-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  routes:
    main:
      path: /user/**
      url: http://localhost:8090
    form:
      path: /form/**
      url: http://localhost:8090
    admin:
      path: /admin/**
      url: http://localhost:8999
    security:
      path: /auth/**
      url: http://localhost:9999/auth
    registration:
      path: /registration/**
      url: http://localhost:9999/registration
    confirm:
      path: /confirm/**
      url: http://localhost:9999/confirm