server:
  port: 8091
spring:
  application:
    name: zuul-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  routes:
    main:
      path: /user/**
      url: http://localhost:8090
    security:
      path: /auth/**
      url: http://localhost:9999/auth